apiVersion: v1
kind: Service
metadata:
  labels:
    app: local-redis
  name: local-redis
spec:
  type: LoadBalancer
  ports:
    - name: "6379"
      port: 6379
      targetPort: 6379
  selector:
    app: local-redis
